#!/bin/bash
#
# tmux_conf
# =======
#
# This script sends a couple of requests over the network to retrieve
# approximate location data, and the current weather for that location. This is
# useful if for example you want to display the current weather in your tmux
# status bar.

API_KEY=""
ZIP_CODE="80301"
COF_LOC="${HOME}/.tmux/"

set -e
mkdir -p $COF_LOC

RET="[ $(hostname) ] ☢"

printf "%s" "$RET" | tee ${COF_LOC}${ZIP_CODE}.nfo

